# -*- coding: utf-8 -*-
"""sms.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rD-T4OuIygTXZKPD9BPIqGBWeO67iLaV
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn. linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

#raw_sms_data = pd.read_csv('/content/spam.csv')



encodings = ['utf-8', 'latin','ISO-8859-1', 'Cp1252']
file_path = '/content/spam.csv'

for encoding in encodings:
    try:
        raw_sms_data = pd.read_csv(file_path, encoding=encoding)
        print(f"File successfully read with encoding: {encoding}")
        break
    except UnicodeDecodeError:
        print(f"Failed to read with encoding: {encoding}")
        continue

if 'raw_sms_data' in locals():
    print("Csv file has been successfully loaded.")
else:
    print("All encoding attempts failed. Unable to read the Csv file.")



print(raw_sms_data)

sms_data = raw_sms_data.where((pd.notnull (raw_sms_data)),' ')

sms_data.head()

sms_data.drop(columns=['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], inplace=True)

sms_data.head()



sms_data.shape

sms_data.replace({'v1': {'spam':0, 'ham': 1}}, inplace=True)

sms_data.head()

X = sms_data['v2']
Y = sms_data['v1']

print(X)

print(Y)

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=3)

print(X.shape)

print(X_train)

print(X.shape, X_train.shape, X_test.shape)

# transform the text data to feature vectors that can be used as input to the Logistic regression
feature_extraction = TfidfVectorizer(min_df = 1, stop_words='english', lowercase=True )

X_train_features = feature_extraction.fit_transform(X_train)
X_test_features = feature_extraction.transform(X_test)
# convert Y_train and Y_test values as integers
Y_train = Y_train.astype('int')
Y_test = Y_test.astype('int')

model = LogisticRegression()

model.fit(X_train_features, Y_train)

prediction_on_training_data =model.predict(X_train_features)

accuracy_on_training_dat = accuracy_score(Y_train, prediction_on_training_data)

print(accuracy_on_training_dat)

# prediction on test data
prediction_on_test_data = model.predict(X_test_features)
accuracy_on_test_data = accuracy_score(Y_test,prediction_on_test_data)

print(accuracy_on_test_data)

input_sms=["Nah I don't think he goes to usf, he lives around here though"]
#convert text to feature vectors
input_data_features =feature_extraction.transform(input_sms)
# making prediction
prediction = model.predict (input_data_features)
print (prediction)
if (prediction[0]==1):
  print ('Ham sms')
else:
  print ('Spam sms')

